spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CRYPTO_GATE_TOKEN
    username: CRYPTO_GATE_APP
    password: cryptogate
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect